### ISSUE TITLE
Fundación "Un municipio sin pobreza "

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-10-mockup-de-aplicacion-web-3-equipo-4#1]
https://www.figma.com/file/SAFmtPJ2qfmcxL3nDTzibb/Untitled?node-id=0%3A1&t=uv7dJysVWX1jIavS-3

**Comment by YaelTrinidad** [comment]
ACTIVIDAD MOCKUP
DE LOS 12 PUNTOS OBTUVISTE 11 EQUIVALENTE A 45.83% DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
